//#include "exptional_use.h"
//#include<exception>
//#include<iostream>
//#include<vector>
//using namespace std;
//
//int main()
//{
//	exptional_use aa;
//	aa.arr.push_back(1);
//	try
//	{
//		aa.test1(aa.arr,0);
//		cout << "0meishi" << endl;
//		aa.test1(aa.arr, 1);
//
//	}
//	catch (exception e)
//	{
//		cout << "here" << endl;
//	}
//
//
//	return 0;
//}